/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package operatorPackage;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author prasu
 */

public class CustView extends javax.swing.JInternalFrame {

    /**
     * Creates new form Customer
     */String url="jdbc:mysql://localhost:3306/operator";
            String un="root";
            String pass="Password@123";
    public CustView() {
        initComponents();
        branch();
         jComboBox1.setSelectedIndex(-1);
        Connection con;
    
       
        try { txtCount.setText("");
            jTableClient.setModel(new DefaultTableModel(null,new String[]{"CUST_NAME","CUST_IP","CUST_CONTACT","OPERATOR NAME"}));
            
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection(url,un,pass);
            
                  Statement st1=con.createStatement();
                  Statement st2=con.createStatement();
                  Statement st3=con.createStatement();
                  String query1="SELECT cust_name,cust_contactno,cust_ip,operator_name FROM operator  op  "
                          + " join customer cus on cus.operator_id=op.operator_id order by op.operator_name;";
                  
                  String query2="SELECT count(*) FROM operator  op  "
                          + " join customer cus on cus.operator_id=op.operator_id order by op.operator_name ;";
                 

       ResultSet rs1=st1.executeQuery(query1);
         ResultSet rs2=st2.executeQuery(query2);
          
         
         rs2.next();
         
         
         txtCount.setText(rs2.getString(1));

        DefaultTableModel model=(DefaultTableModel)jTableClient.getModel();
        while(rs1.next())
        {model.addRow(new String[]{rs1.getString(1),rs1.getString(2),rs1.getString(3),rs1.getString(4)});         
        //System.out.println(rs1.getString(2));
        }
        
        }       
        
        catch (ClassNotFoundException ex) {
            Logger.getLogger(CustView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CustView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
            
            
                

    public void autoId ()
    {
        
        
        
    }
    
    public void branch()
    {Connection con;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection(url,un,pass);
            Statement st=con.createStatement();
        
        ResultSet rs=st.executeQuery("select operator_name from operator;");
        
        jComboBox1.removeAllItems();
        while(rs.next())
        {jComboBox1.addItem(rs.getString(1));
       
        }
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewUser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NewUser.class.getName()).log(Level.SEVERE, null, ex);
        }
            
           
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClient = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtCount = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCust = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(0, 102, 153));
        setClosable(true);
        setForeground(new java.awt.Color(255, 123, 162));
        setIconifiable(true);
        setMinimumSize(new java.awt.Dimension(1366, 768));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jTableClient.setAutoCreateRowSorter(true);
        jTableClient.setBackground(new java.awt.Color(0, 79, 58));
        jTableClient.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTableClient.setForeground(new java.awt.Color(255, 255, 255));
        jTableClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CUST NAME", "CUST IP", "CUST CONTACT", "OPERATOR NAME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableClient.setGridColor(new java.awt.Color(0, 0, 0));
        jTableClient.setRowSelectionAllowed(false);
        jTableClient.setShowGrid(true);
        jScrollPane1.setViewportView(jTableClient);

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 0, 51));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton3.setText("FILTER");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });

        txtCount.setBackground(new java.awt.Color(255, 255, 255));
        txtCount.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtCount.setForeground(new java.awt.Color(0, 0, 0));
        txtCount.setText("jTextField1");
        txtCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(176, 176, 176)
                                .addComponent(txtCount, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(104, 104, 104))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCount, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel8))
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("ALL CUSTOMERS");

        jLabel2.setText("Operator Name");

        jLabel4.setText("Customer Name");

        txtCust.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCustKeyPressed(evt);
            }
        });

        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(442, 442, 442)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCust, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Connection con;
        String name="";
       if(jComboBox1.getSelectedIndex() != -1)
       {name=jComboBox1.getSelectedItem().toString();
       }
       
    
       
        String cust_name=txtCust.getText().toUpperCase();
       
        try {
            jTableClient.setModel(new DefaultTableModel(null,new String[]{"CUST_NAME","CUST_IP","CUST_CONTACT","OPERATOR NAME "}));
            
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection(url,un,pass);
            
                  Statement st1=con.createStatement();
                    Statement st2=con.createStatement();
                    
                  String query1="SELECT cust_name,cust_contactno,cust_ip,operator_name FROM operator  op  "
                          + " join customer cus on cus.operator_id=op.operator_id ";
                  
                  String query2="SELECT count(*) FROM operator  op  "
                          + " join customer cus on cus.operator_id=op.operator_id ";
                          
                  
                  if(name.length()!=0)
                  {
                      
                      query1=query1+" WHERE op.operator_name='"+name+"'";
                     query2=query2+"WHERE op.operator_name='"+name+"'";
                     


                  }
                 
                  if(cust_name.length()!=0)
                  { cust_name="%"+cust_name+"%";
                      if(name.length()==0 )
                      {query1=query1+" WHERE cust_name like'"+cust_name+"'";
                      query2=query2+"WHERE cust_name like'"+cust_name+"'";
                    
                      }
                      
                      else
                  {query1=query1+" AND cust_name like'"+cust_name+"'";
                  query2=query2+"AND cust_name like'"+cust_name+"'";
                  
                  }
                  }
                  
                  query1=query1+";";
                  query2=query2+";";
                  
                  System.out.print(query2);
        
        ResultSet rs1=st1.executeQuery(query1);
         ResultSet rs2=st2.executeQuery(query2);
          
         rs2.next();
         
         
         txtCount.setText(rs2.getString(1));

        DefaultTableModel model=(DefaultTableModel)jTableClient.getModel();
        while(rs1.next())
        {model.addRow(new String[]{rs1.getString(1),rs1.getString(2),rs1.getString(3),rs1.getString(4)});         
        }
        
        }     
        
        catch (ClassNotFoundException ex) {
            Logger.getLogger(CustView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CustView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      jComboBox1.setSelectedIndex(-1);
        Connection con;
    
       
        try { txtCount.setText("");
            jTableClient.setModel(new DefaultTableModel(null,new String[]{"CUST_NAME","CUST_IP","CUST_CONTACT","OPERATOR NAME"}));
            
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection(url,un,pass);
            
                  Statement st1=con.createStatement();
                  Statement st2=con.createStatement();
                  
                  String query1="SELECT cust_name,cust_contactno,cust_ip,operator_name FROM operator  op  "
                          + " join customer cus on cus.operator_id=op.operator_id order by op.operator_name;";
                  
                  String query2="SELECT count(*) FROM operator  op  "
                          + " join customer cus on cus.operator_id=op.operator_id order by op.operator_name;";
                 

       ResultSet rs1=st1.executeQuery(query1);
         ResultSet rs2=st2.executeQuery(query2);
          
         
         rs2.next();
         
         
         txtCount.setText(rs2.getString(1));

        DefaultTableModel model=(DefaultTableModel)jTableClient.getModel();
        while(rs1.next())
        {model.addRow(new String[]{rs1.getString(1),rs1.getString(2),rs1.getString(3),rs1.getString(4)});         
        //System.out.println(rs1.getString(2));
        }
        
        }       
        
        catch (ClassNotFoundException ex) {
            Logger.getLogger(CustView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CustView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        // TODO add your handling code here:
        
         
    }//GEN-LAST:event_jButton3KeyPressed

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {  Connection con;
        String name="";
       if(jComboBox1.getSelectedIndex() != -1)
       {name=jComboBox1.getSelectedItem().toString();
       }
       
    
       
        String cust_name=txtCust.getText().toUpperCase();
       
        try {
            jTableClient.setModel(new DefaultTableModel(null,new String[]{"CUST_NAME","CUST_IP","CUST_CONTACT","OPERATOR NAME "}));
            
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection(url,un,pass);
            
                  Statement st1=con.createStatement();
                    Statement st2=con.createStatement();
                    
                  String query1="SELECT cust_name,cust_contactno,cust_ip,operator_name FROM operator  op  "
                          + " join customer cus on cus.operator_id=op.operator_id ";
                  
                  String query2="SELECT count(*) FROM operator  op  "
                          + " join customer cus on cus.operator_id=op.operator_id ";
                          
                  
                  if(name.length()!=0)
                  {
                      
                      query1=query1+" WHERE op.operator_name='"+name+"'";
                     query2=query2+"WHERE op.operator_name='"+name+"'";
                     


                  }
                 
                  if(cust_name.length()!=0)
                  { cust_name="%"+cust_name+"%";
                      if(name.length()==0 )
                      {query1=query1+" WHERE cust_name like'"+cust_name+"'";
                      query2=query2+"WHERE cust_name like'"+cust_name+"'";
                    
                      }
                      
                      else
                  {query1=query1+" AND cust_name like'"+cust_name+"'";
                  query2=query2+"AND cust_name like'"+cust_name+"'";
                  
                  }
                  }
                  
                  query1=query1+";";
                  query2=query2+";";
                  
                  System.out.print(query2);
        
        ResultSet rs1=st1.executeQuery(query1);
         ResultSet rs2=st2.executeQuery(query2);
          
         rs2.next();
         
         
         txtCount.setText(rs2.getString(1));

        DefaultTableModel model=(DefaultTableModel)jTableClient.getModel();
        while(rs1.next())
        {model.addRow(new String[]{rs1.getString(1),rs1.getString(2),rs1.getString(3),rs1.getString(4)});         
        }
        
        }     
        
        catch (ClassNotFoundException ex) {
            Logger.getLogger(CustView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CustView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        }
    }//GEN-LAST:event_jComboBox1KeyPressed

    private void txtCustKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {  Connection con;
        String name="";
       if(jComboBox1.getSelectedIndex() != -1)
       {name=jComboBox1.getSelectedItem().toString();
       }
       
    
       
        String cust_name=txtCust.getText().toUpperCase();
       
        try {
            jTableClient.setModel(new DefaultTableModel(null,new String[]{"CUST_NAME","CUST_IP","CUST_CONTACT","OPERATOR NAME "}));
            
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection(url,un,pass);
            
                  Statement st1=con.createStatement();
                    Statement st2=con.createStatement();
                    
                  String query1="SELECT cust_name,cust_contactno,cust_ip,operator_name FROM operator  op  "
                          + " join customer cus on cus.operator_id=op.operator_id ";
                  
                  String query2="SELECT count(*) FROM operator  op  "
                          + " join customer cus on cus.operator_id=op.operator_id ";
                          
                  
                  if(name.length()!=0)
                  {
                      
                      query1=query1+" WHERE op.operator_name='"+name+"'";
                     query2=query2+"WHERE op.operator_name='"+name+"'";
                     


                  }
                 
                  if(cust_name.length()!=0)
                  { cust_name="%"+cust_name+"%";
                      if(name.length()==0 )
                      {query1=query1+" WHERE cust_name like'"+cust_name+"'";
                      query2=query2+"WHERE cust_name like'"+cust_name+"'";
                    
                      }
                      
                      else
                  {query1=query1+" AND cust_name like'"+cust_name+"'";
                  query2=query2+"AND cust_name like'"+cust_name+"'";
                  
                  }
                  }
                  
                  query1=query1+";";
                  query2=query2+";";
                  
                  System.out.print(query2);
        
        ResultSet rs1=st1.executeQuery(query1);
         ResultSet rs2=st2.executeQuery(query2);
          
         rs2.next();
         
         
         txtCount.setText(rs2.getString(1));

        DefaultTableModel model=(DefaultTableModel)jTableClient.getModel();
        while(rs1.next())
        {model.addRow(new String[]{rs1.getString(1),rs1.getString(2),rs1.getString(3),rs1.getString(4)});         
        }
        
        }     
        
        catch (ClassNotFoundException ex) {
            Logger.getLogger(CustView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CustView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
       
            
        }
    }//GEN-LAST:event_txtCustKeyPressed

    private void txtCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableClient;
    private javax.swing.JTextField txtCount;
    private javax.swing.JTextField txtCust;
    // End of variables declaration//GEN-END:variables
}
